---
nodes_list:
  - {ip: '194.5.206.100', name: 'master1.nazarbazi.ir'}
  - {ip: '194.5.206.177', name: 'master2.nazarbazi.ir'}
  - {ip: '194.5.206.191', name: 'worker1.nazarbazi.ir'}
  - {ip: '194.5.206.146', name: 'worker2.nazarbazi.ir'}
  - {ip: '194.5.206.32', name: 'loadbalancer.nazarbazi.ir'}

master:
  init_ip: 194.5.206.100

join_list:
  - {ip: '194.5.206.191'}
  - {ip: '194.5.206.146'}

dev_ip:
  ansible_facts.eth0.ipv4.address
